### ISSUE TITLE
`rustlings watch` throws main panic at `Result::unwrap()`

### ISSUE THREAD

**Issue by naltun** [rustlings/rustlings#109]
![image](https://user-images.githubusercontent.com/7507990/51684363-e1402900-1fb9-11e9-9fb0-7d0f61a43250.png)

I have run `rustlings watch` with `RUST_BACKTRACE=1` and got this:
![image](https://user-images.githubusercontent.com/7507990/51684499-2ebc9600-1fba-11e9-90ad-b8903dd24ac6.png)

**Comment by komaeda** [comment]
are you running rustlings from within the directory you cloned?

**Comment by naltun** [comment]
@komaeda Nope, that fixed it. I figured because I was told to add `$HOME/.cargo/bin` (where `rustlings` is stored) to my `PATH`, that meant I could run it anywhere. This can be closed.
