### ISSUE TITLE
What about creating an interactive way to run it on terminal?

### ISSUE THREAD

**Issue by douglascorrea** [rustlings/rustlings#21]
Hi,
I'm starting to learn Rust, and this repo is a very good start point, thank you @carols10cents!

I was thinking that it could be even better if we can transform it in a terminal lessons like nodeschool.io and swirlstats.com

I'm still learning Rust but I'll be glad to help.

**Comment by nokaa** [comment]
[https://play.rust-lang.org/](https://play.rust-lang.org/) could probably be used for this.

**Comment by douglascorrea** [comment]
@nokaa the nice part of nodeschool is that run from the terminal, and it makes easy to user follow up with the tutorial.
try this `npm install -g javascripting`

**Comment by carols10cents** [comment]
> https://play.rust-lang.org/ could probably be used for this.

@nokaa Is there a way the playground can be used as an API? Is that what you're suggesting?

The exercism CLI could be a good example too :) I'll think about how we could do this @douglascorrea, thank you for the suggestion!!

**Comment by nokaa** [comment]
@douglascorrea I misunderstood. I confused nodeschool with something else I had seen, which provided an in-browser terminal to run examples.

@carols10cents I misunderstood what was being suggested.

**Comment by svanellewee** [comment]
I realise I'm a bit late to the party here, but I was just wondering if something like https://github.com/carols10cents/rustlings/pull/65 would help anyone else?
