### ISSUE TITLE
Exercises involving derive

### ISSUE THREAD

**Issue by carols10cents** [rustlings/rustlings#28]
Ugh i don't really want it to just be "oh this is missing a `#[derive(whatever)]`", but I do want the usage of derives to be introduced somehow.... hmmmm...

**Comment by anuragsoni** [comment]
How about an exercise involving implementing a trait and then contrasting that with the option to 
```#[derive(Trait)]```

Something along the lines of:
```rust
use std::fmt;

struct Point {
    x: i32,
    y: i32,
}

impl fmt::Debug for Point {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Point {{ x: {}, y: {} }}", self.x, self.y)
    }
}

let origin = Point { x: 0, y: 0 };

println!("The origin is: {:?}", origin);
```

vs
```rust
#[derive(Debug)]
struct Point {
    x: i32,
    y: i32,
}
let origin = Point { x: 0, y: 0 };

println!("The origin is: {:?}", origin);

```

**Comment by mwilli20** [comment]
I don't know if the idea was to have more of these than what exists but https://github.com/carols10cents/rustlings/blob/master/ex3.rs already exists for this. It is a very minimal example to show off the very concept of #[derive(Debug)]. Unless there is a specific need for an issue just like this again, I feel like this could be closed.
