### ISSUE TITLE
Exercises demonstrating lifetimes

### ISSUE THREAD

**Issue by rschmertz** [rustlings/rustlings#51]

**Comment by evanjs** [comment]
Any reason this was closed? 
I think people could definitely benefit from a lifetimes exercise in this repo.

**Comment by ilyakmet** [comment]
I think so

**Comment by missingdays** [comment]
Any updates on this issue? I did all the exercises and was suprised there were none for the lifetime.

**Comment by fabienengels** [comment]
Just finished too, and got the same thought :)
