### ISSUE TITLE
Open Exercise Links in New Tab

### ISSUE THREAD

**Issue by juliusdelta** [rustlings/rustlings#59]
I ran threw some exercises in my spare time, in chrome. The links don't open in a new tab, so maybe replacing them with HTML instead of pure markdown may be a good option so the resource can stay open.

Example:
`<a href="http://example.com" target="_blank">http://example.com</a>` = <a href="http://example.com" target="_blank">http://example.com</a>

I can submit a PR if this gets "approved" by a maintainer 😄.

**Comment by carols10cents** [comment]
I'm into this, except I don't generate these links by hand, I use this little prlink script @btbytes made: https://github.com/btbytes/prlink If you make the PR over there, I would be glad to start using it!

**Comment by juliusdelta** [comment]
Interesting. I'll look into it and see if we can get that setup! It'd be a great rust exercise for me.
