### ISSUE TITLE
Integrate pnkfelix's exercises

### ISSUE THREAD

**Issue by carols10cents** [rustlings/rustlings#6]
Great stuff here!!

http://pnkfelix.github.io/rust-examples-icfp2014/
http://pnkfelix.github.io/cyot/tutorial/exercises/ex_part_1.html
http://pnkfelix.github.io/cyot/tutorial/exercises/ex_part_2.html
http://pnkfelix.github.io/cyot/tutorial/exercises/ex_part_3.html

**Comment by oe** [comment]
Closing for now because of #80!
