### ISSUE TITLE
Update "errors" exercises to use "?" instead of try!() macro?

### ISSUE THREAD

**Issue by gerv** [rustlings/rustlings#64]
My understanding is that recent Rust versions no longer use the try! macro; since Rust 1.13, the "?" operator is used instead. So do the latter "errors" exercises need updating?

**Comment by carols10cents** [comment]
That sounds good!

**Comment by Mathias-L** [comment]
Rust newbie here, I thought about errors2.rs and wondered why try! is suggested there. I got it working perfectly directly returning "parse.map()". The solution is basically directly mentioned in the [first edition](https://doc.rust-lang.org/stable/book/first-edition/error-handling.html#parsing-integers). Is there any reason to use try! there?
