### ISSUE TITLE
Wording ambiguous - what should be changed?

### ISSUE THREAD

**Issue by ERnsTL** [rustlings/rustlings#74]
Greetings, to me, the wording of several exercises is ambiguous, for example in ```result1.rs```:

*Make this test pass!*

Until looking at the hints, I was not sure if I should modify the code or the test in order to make it pass.

This is true for a few other exercises which are two-part (eg. main + a function or main + a macro or main + a test) as well (*make it compile!*). Which part should stay unchanged and what can be changed to make it work?

In a few exercises, this is made clear, but in others it is ambiguous.

Greetings

**Comment by carols10cents** [comment]
Thanks! It would be helpful if you would list out which exercises are ambiguous, and what made you unsure, to be able to fix these!
