### ISSUE TITLE
Get inspiration from koans

### ISSUE THREAD

**Issue by carols10cents** [rustlings/rustlings#8]
http://www.rubykoans.com/

There's something that isn't quite what I'm going for about koans, maybe that it's really contrived, maybe that the last time i tried them it... started too early? moved at a weird pace-- hitting really simple stuff but then moving on immediately?

Or maybe I just gave up on the koans too early?

I think I'm going for lots of similar-but-slightly-different exercises/situations. Like repeat one concept over and over until you get it, then move on to the next thing. Maybe.

**Comment by oe** [comment]
superseded by https://github.com/rustlings/rustlings/issues/80, quite literally
