### ISSUE TITLE
Improve README with more instructions in how to work locally

### ISSUE THREAD

**Issue by mrcosta** [rustlings/rustlings#83]
Maybe it's just me, but I like to work locally and even push the changes to my local repo for future references.

I took some time to figure out how the dynamics of the project works. This is exactly what I did in my local environment:

* clone the project
* `cargo check` (success)
* I fixed the `variables1.rs` and I was thinking "hum...ok, how can I just this one?"
* `cargo run` (success)
* I checked the local changes and then realized that the README was different, I open the new link and realized that my change also opened in the editor. It was just then that I realized how it works.

The idea is to improve a little bit the instructions.

**Comment by oe** [comment]
Hi @mrcosta! We're currently in the process of rewriting Rustlings, as can be seen in #80! The proposed version would work a lot like the one you found out here, but it's not quite done yet. I'll merge this in regardless since we still have the old one pointing here!
